### PR TITLE
fixed extension viewlet issues

### LINKED ISSUE #1167: Extensions all show as having 0 downloads on Windows install
- SQL Operations Studio Version: 0.27.3 Windows

Steps to Reproduce:
- Open Ops Studio and go to the extensions view
- Note that all extensions show with 0 downloads. Should hide this until we have a proper count
- I'm testing on the public release, maybe this is fixed internally? It doesn't happen on Mac.

image

### PR DESCRIPTION
**Pull request by llali**
Fixed couple of issues in the extension viewlet:

1. The license and repository was not displayed for extensions
2. Removed the small "rating" and "install count" icons 
fixes #1167
3. Issue tracker now works for extension and it's possible to create issue for extension but the url used to create github was returning 404. the reason was a bug in vs code which doesn't add "?" to the url. Had to fix the issue in vs code but for now fixing it in sqlops

image

### CODE REVIEW

File: src/vs/code/electron-browser/issue/issueReporterMain.ts [hunk 1]
```diff
@@ -771,7 +771,8 @@ export class IssueReporter extends Disposable {
 			}
 		}
 
-		const queryStringPrefix = product.reportIssueUrl.indexOf('?') === -1 ? '?' : '&';
+		// {{SQL CARBON EDIT}}
+		const queryStringPrefix = repositoryUrl.indexOf('?') === -1 ? '?' : '&';
```
Comment (kburtram) [inline src/vs/code/electron-browser/issue/issueReporterMain.ts]: did you get this fix accepted upstream in vscode?

Comment (llali) [reply src/vs/code/electron-browser/issue/issueReporterMain.ts]: no I have t create a PR in their repository
