### PR TITLE
Webview tab

### LINKED ISSUE #631: Dashboard.tabs contribution expects single object, not array
- SQL Operations Studio Version:

Steps to Reproduce:
- Create an extension with tab contribution
- Add an array (which is claimed to be supported) rather than a single object
- Note that there's a warning showing this isn't supported, expects an object instead.

```
        "dashboard.tabs": [
            {
                
            }
        ],
```
image

### PR DESCRIPTION
**Pull request by anthonydresser**
Adds a webview tab contribution using the `isWebview` property when contributing a tab. Functionally it works the same as webview widget and uses the same extension apis.

fixes #631

### CODE REVIEW

File: src/sql/parts/dashboard/dashboardWebviewTab.component.ts [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+import { TabConfig } from 'sql/parts/dashboard/common/dashboardWidget';
+import { DashboardServiceInterface } from 'sql/parts/dashboard/services/dashboardServiceInterface.service';
+import { IDashboardWebview } from 'sql/services/dashboardWebview/common/dashboardWebviewService';
+
+@Component({
+	template: '<div></div>',
+	selector: 'dashboard-webview-tab',
+	providers: [{ provide: DashboardTab, useExisting: forwardRef(() => DashboardWebviewTab) }]
+})
+export class DashboardWebviewTab extends DashboardTab implements OnInit, IDashboardWebview {
```
Comment (AbbiePetcht) [inline src/sql/parts/dashboard/dashboardWebviewTab.component.ts]: >DashboardWebviewTab [](start = 13, length = 19)

Should we move this inside the common folder? It should be the same folder is dashboardWidgetTab.Component

Comment (anthonydresser) [reply src/sql/parts/dashboard/dashboardWebviewTab.component.ts]: It's not realyl a common component. Its a stand alone component so I think actually the dashboardwidget tab should be pulled out.
