### PR TITLE
Swallow error on context view  when disposing children

### LINKED ISSUE #1653: dropdown control issue
Steps to Reproduce:

1. Open the connect to database dialog
2. Click the Connection type and open the dropdown
3. Keep the Connection type dropdown opened and try to open the authentication type dropdown

actual result:
Got the following error:

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at Object.dispose (git/sqlopsstudio/out/vs/base/browser/ui/selectBox/selectBoxCustom.js:293)
    at ContextView.hide (git/sqlopsstudio/out/vs/base/browser/ui/contextview/contextview.js:163)
    at ContextView.show (git/sqlopsstudio/out/vs/base/browser/ui/contextview/contextview.js:89)
    at ContextViewService.showContextView (git/sqlopsstudio/out/vs/platform/contextview/browser/contextViewService.js:32)
    at SelectBoxList.showSelectDropDown (git/sqlopsstudio/out/vs/base/browser/ui/selectBox/selectBoxCustom.js:267)
    at HTMLSelectElement.<anonymous> (git/sqlopsstudio/out/vs/base/browser/ui/selectBox/selectBoxCustom.js:104)

### PR DESCRIPTION
**Pull request by anthonydresser**
fixes #1653

### CODE REVIEW

File: src/vs/base/browser/ui/selectBox/selectBoxCustom.ts [hunk 1]
```diff
@@ -397,8 +397,16 @@ export class SelectBoxList implements ISelectBoxDelegate, IDelegate<ISelectOptio
 		container.appendChild(this.selectDropDownContainer);
 
 		this.layoutSelectDropDown();
+
+		// {{SQL EDIT}}
```
Comment (alanrenmsft) [inline src/vs/base/browser/ui/selectBox/selectBoxCustom.ts]: remove this comment?

Comment (MattIrv) [inline src/vs/base/browser/ui/selectBox/selectBoxCustom.ts]: To match the rest this should be `// {{SQL CARBON EDIT}}`

Comment (kburtram) [reply src/vs/base/browser/ui/selectBox/selectBoxCustom.ts]: Yes, please make this `// {{SQL CARBON EDIT}}` so that it's easy to search for all our patches to VS Code.
