### PR TITLE
fixed extension filter and search

### LINKED ISSUE #1262: Extension auto-update shouldn't automatically open extension websites
- SQL Operations Studio Version: master 1811dfa

Steps to Reproduce:
1. Install an out of date third-party extension that installs from a web link instead of a vsix
2. Enable extension auto update if not enabled (`extensions.autoUpdate`, it's enabled by default)
3. Restart SQL Ops Studio

Actual behavior: The extension's webpage pops up the moment SQL Ops Studio opens without any indication why
Expected behavior: Auto update does not apply to extensions that install via web links

### PR DESCRIPTION
**Pull request by llali**
fixes #1262 and #1165

### CODE REVIEW

File: src/vs/platform/extensionManagement/node/extensionGalleryService.ts [hunk 1]
```diff
@@ -24,6 +24,7 @@ import { readFile } from 'vs/base/node/pfs';
 import { writeFileAndFlushSync } from 'vs/base/node/extfs';
 import { generateUuid, isUUID } from 'vs/base/common/uuid';
 import { values } from 'vs/base/common/map';
+import { forEach } from '../../../base/common/event';
```
Comment (kburtram) [inline src/vs/platform/extensionManagement/node/extensionGalleryService.ts]: we should add `// {{SQL CARBON EDIT}}` tag to each edit in this file so we don't blow them away in the next merge

Comment (kburtram) [reply src/vs/platform/extensionManagement/node/extensionGalleryService.ts]: I recommend using absolute paths for includes.  vs code moves there files around periodically.

File: src/vs/platform/extensionManagement/node/extensionGalleryService.ts [hunk 2]
```diff
@@ -466,6 +469,43 @@ export class ExtensionGalleryService implements IExtensionGalleryService {
...
+					}
+					return 0;
+				});
+				break;
+			case SortBy.Title:
+				filteredExtensions.sort((a: IRawGalleryExtension, b: IRawGalleryExtension) => {
+					if (a && b && a.displayName && b.displayName) {
+						return a.displayName < b.displayName ? -1 : 1;
+					}
+					return 0;
```
Comment (kburtram) [inline src/vs/platform/extensionManagement/node/extensionGalleryService.ts]: seems like this will have arbitrary sort order if one extension has no display name and the other does.  Not sure it's a problem, just seems non-deterministic

File: src/vs/platform/extensionManagement/node/extensionGalleryService.ts [hunk 3]
```diff
@@ -466,6 +469,43 @@ export class ExtensionGalleryService implements IExtensionGalleryService {
...
+				});
+				break;
+			default:
```
Comment (kburtram) [inline src/vs/platform/extensionManagement/node/extensionGalleryService.ts]: nit: do we need a default clause if we don't do anything there?

File: src/vs/platform/extensionManagement/node/extensionGalleryService.ts (hunk 1 above)
Comment (MattIrv) [inline src/vs/platform/extensionManagement/node/extensionGalleryService.ts]: Looks like you didn't mean to include this anyway? I don't see it used
