### PR TITLE
Fix model view editor where switching between different type of editors remove the dom

### LINKED ISSUE #1547: Model view editor dom is removed when switch to different editor type

### PR DESCRIPTION
**Pull request by AbbiePetcht**
Fix #1547: Model view editor dom is removed when switch to different editor type

### CODE REVIEW

File: src/sql/parts/modelComponents/modelEditor/modelViewInput.ts [hunk 1]
```diff
@@ -46,14 +53,30 @@ export class ModelViewInput extends EditorInput {
...
+	public appendViewModelContainer(): void {
+		if (!this._dialogPane) {
+			this.createDialogPane();
+		}
+		if (!this._container.contains(this._dialogPaneContainer)) {
+			this._container.appendChild(this._dialogPaneContainer);
+		}
+	}
+
+	public removeModelContainer(): void {
```
Comment (MattIrv) [inline src/sql/parts/modelComponents/modelEditor/modelViewInput.ts]: Minor: a few inconsistent names... `removeModelContainer` here, `appendViewModelContainer` above, and `hideOrRemoveModelViewContainer` in the editor
