### PR TITLE
Fix insert ordering in scrollable splitview

### LINKED ISSUE #2319: Result order is wrong when a query has multiple results
- SQL Operations Studio Version: master 4cce29e

Steps to Reproduce:
- Run the following query
```
select 1,2,3
select 4,5,6
```

Actual behavior: The "4,5,6" results are displayed above the "1,2,3" results
Expected behavior: The "1,2,3" results should be displayed first

Additionally if you run the query again then only the "1,2,3" results will show up

Results are out of order, with the 1,2,3 results shown underneath the 4,5,6 results

@anthonydresser looks like this is related to your grid changes

### PR DESCRIPTION
**Pull request by anthonydresser**
fixes #2319

### CODE REVIEW

File: src/sql/parts/query/editor/gridPanel.ts [hunk 1]
```diff
@@ -156,6 +156,8 @@ export class GridPanel extends ViewletPanel {
 			tables.push(table);
 		}
 
+		// possible to need a sort?
```
Comment (MattIrv) [inline src/sql/parts/query/editor/gridPanel.ts]: Looks like you meant to look into this?

Comment (anthonydresser) [reply src/sql/parts/query/editor/gridPanel.ts]: No, this is mainly a note for later, current we run the queries sychronously so I'm pretty sure its impossible for the result sets to come out of order. But in the future this may not be the case.
