### PR TITLE
Bug/keyboard issue in manange linked account

### LINKED ISSUE #1398: Should show add message and add account account button when linked account is empty
- SQL Operations Studio Version:

Steps to Reproduce:

### LINKED ISSUE #1399: Linked account tab is broken when the view is collapsed
image

### PR DESCRIPTION
**Pull request by AbbiePetcht**
Fix #1398: Should show add message and add account account button when linked account is empty 

Fix #1399: Linked account tab is broken when the view is collapsed 

image

### CODE REVIEW

File: src/sql/parts/accountManagement/accountDialog/accountDialog.ts [hunk 1]
```diff
@@ -199,10 +249,16 @@ export class AccountDialog extends Modal {
...
+
+		if (newProvider.initialAccounts.length > 0 && this._splitViewContainer.hidden) {
+			this.showSplitView();
+		}
+
 		this.layout();
 
-		// Store the view for the provider
+		// Store the view for the provider and action
 		this._providerViews[newProvider.addedProvider.id] = providerView;
```
Comment (kburtram) [inline src/sql/parts/accountManagement/accountDialog/accountDialog.ts]: does it make more sense to have one map that points to an object that contains both `providerView` and `addAccountAction`?  If there's only ever two things indexed from provider id then two maps is probably fine, but it doesn't seem scalable if there could be more.
