### PR TITLE
Rearrange done and cancel buttons and dispose dialogs correctly

### LINKED ISSUE #1416: ModelView dialog: "Cancel" button should be rightmost
- SQL Operations Studio Version:

Steps to Reproduce:
- All other dialogs have Cancel as default rightmost button
- Modelview based dialogs to not, it's left of "Done"

### PR DESCRIPTION
**Pull request by MattIrv**
This PR fixes 2 small issues with model view dialogs:
- The done and cancel buttons were in the wrong order compared to the rest of our UI (e.g. the connection dialog) - fixes #1416
- Dialogs with multiple tabs only destroyed one of the tabs when closed - part of #1414 but we still need to call close on each model view

### CODE REVIEW

File: src/sql/platform/dialog/dialogModal.ts [hunk 1]
```diff
@@ -66,12 +66,12 @@ export class DialogModal extends Modal {
 			});
 		}
 
-		this._cancelButton = this.addDialogButton(this._dialog.cancelButton, () => this.cancel(), false);
-		this.updateButtonElement(this._cancelButton, this._dialog.cancelButton);
-		this._dialog.cancelButton.registerClickEvent(this._onCancel.event);
 		this._doneButton = this.addDialogButton(this._dialog.okButton, () => this.done(), false);
```
Comment (kevcunnane) [inline src/sql/platform/dialog/dialogModal.ts]: Super-minor: if this is repeated code, how about putting in its own function? 😄

Comment (MattIrv) [reply src/sql/platform/dialog/dialogModal.ts]: I was able to get rid of the `updateButtonElement` line by moving it into the `addDialogButton` function call (which is supposed to address the repetition point you raised already). Unfortunately since the buttons need to be set up to do the done/cancel actions it's hard to combine the remaining lines
