### PR TITLE
Fixes the 'undefined' in connection tree when capabilities not loaded

### LINKED ISSUE #554: Previously saved connections show as 'undefined' on first run after upgrading from Jan. release to recent builds
- SQL Operations Studio Version: Observed by upgrading from the [January release](https://docs.microsoft.com/en-us/sql/sql-operations-studio/download) to a 1/25/18 daily build

Steps to Reproduce:
1. Run the January release version of SQL Ops Studio, starting with no saved connections or connection groups
2. Save a connection
3. Close the January release and open the 1/25/18 daily build
4. Look at OE: the connection you saved on the old version shows as 'undefined' and you can't connect to it

screen shot 2018-01-25 at 2 56 44 pm

This repros on both Mac and Windows for me. I haven't tried Linux yet. The 1/25/18 build is just the one I noticed the problem with, not necessarily the first one that this repros for.
Workaround: Restart SQL Ops Studio

### PR DESCRIPTION
**Pull request by llali**
fixes #554

These are the things I fixed this PR:

1. If any of the connections in the tree has invalid title ('undefined' in the label), the label is changed to 'Loading ...'  
2. Updating the cached capabilities when the capabilities service is loaded.  
3. Refreshing the tree when capabilities service has the metadata ready so the tree node with "loading ..." in the label will change to the connection label

When capabilities cache is empty or metadata is different, the tree would look like this:
image

And after the capabilities service is ready and has the updated metadata, the tree would refresh to display the correct labels

### CODE REVIEW

File: src/sql/parts/connection/common/connectionConfig.ts [hunk 1]
```diff
@@ -102,8 +107,10 @@ export class ConnectionConfig implements IConnectionConfig {
 		} else {
 			let capabilities = this._capabilitiesService.getCapabilities();
 			if (capabilities) {
+				console.info('capabilities ' + capabilities.length);
 				let providerCapabilities = capabilities.find(c => c.providerName === providerName);
 				if (providerCapabilities) {
+					console.info('capabilities 2 ' + providerCapabilities);
```
Comment (MattIrv) [inline src/sql/parts/connection/common/connectionConfig.ts]: remove these before merging

File: src/sql/parts/connection/common/providerConnectionInfo.ts [hunk 2]
```diff
@@ -104,6 +104,23 @@ export class ProviderConnectionInfo implements data.ConnectionInfo {
 		this.options[name] = value;
 	}
 
+	/**
+	 * Returns the title of the connection
+	 */
+	public get title(): string {
+		let databaseName = this.databaseName ? this.databaseName : '<default>';
+		let userName = this.userName ? this.userName : 'Windows Authentication';
```
Comment (MattIrv) [inline src/sql/parts/connection/common/providerConnectionInfo.ts]: I know it was like this in the old code but `<default>` and `Windows Authentication` should probably be localized

File: src/sql/parts/registeredServer/viewlet/serverTreeRenderer.ts [hunk 3]
```diff
@@ -146,9 +147,10 @@ export class ServerTreeRenderer implements IRenderer {
 			}
 		}
 
-		let databaseName = connection.databaseName ? connection.databaseName : '<default>';
-		let userName = connection.userName ? connection.userName : "Windows Authentication";
-		let label = connection.serverName + ', ' + databaseName + ' (' + userName + ')';
+		let label = connection.title;
+		if (!connection.isConnectionOptionsValid) {
+			label = localize('loading', 'Loading ...');
```
Comment (MattIrv) [inline src/sql/parts/registeredServer/viewlet/serverTreeRenderer.ts]: I think this should be "Loading..." (without the space) to be consistent with other parts of the code
