### PR TITLE
clear the widget error every time it refreshes

### LINKED ISSUE #1014: sp_whoisactive widgets return no results when refreshed
SQL Operations Studio Version: March public preview 0.27.3

Steps to Reproduce:
1. Open a dashboard for a server where sp_whoisactive is installed and go to the sp_whoisactive dashboard tab. All the widgets will show values
2. Click on any of the widgets to refresh. The refresh will fail

In addition to failing, the widget also renders the "No results to show" message on top of the old data:
"No results to show" message is on top of old dashboard data

### PR DESCRIPTION
**Pull request by AbbiePetcht**
Fix #1014: sp_whoisactive widgets return no results when refreshed

### CODE REVIEW

File: src/sql/parts/dashboard/widgets/insights/insightsWidget.component.ts [hunk 1]
```diff
@@ -203,6 +210,9 @@ export class InsightsWidget extends DashboardWidget implements IDashboardWidget,
 	private _updateChild(result: SimpleExecuteResult): void {
 		this.componentHost.viewContainerRef.clear();
```
Comment (anthonydresser) [inline src/sql/parts/dashboard/widgets/insights/insightsWidget.component.ts]: can you instead change it to just do
```` typescript
this.componentHost.viewContainerRef.clear();
this.error = undefined;
````
in this section.
