### PR TITLE
Fix for duplicate extensions shown in "Save File" dialog.

### LINKED ISSUE #760: Save Query dialog shows *.sql twice
- SQL Operations Studio Version: sqlops 0.26.6 (49bf9163461901730033f85f69220ab4db44045f, 2018-02-14T22:22:52.051Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1. Open a new query window.
2. Select Save
3. Notice the SQL file type is listed as (*.sql;*.sql;*.dsql)

### PR DESCRIPTION
**Pull request by ntovas**
In the file save dialog if a language have 2 or more configuration files in /extensions folder that contains the same extensions it adds the extension again. 
Fixes #760

### CODE REVIEW

File: src/vs/editor/common/services/languagesRegistry.ts [hunk 1]
```diff
@@ -128,7 +128,9 @@ export class LanguagesRegistry {
 		if (Array.isArray(lang.extensions)) {
 			for (let extension of lang.extensions) {
 				mime.registerTextMime({ id: langId, mime: primaryMime, extension: extension }, this._warnOnOverwrite);
-				resolvedLanguage.extensions.push(extension);
+				if (!resolvedLanguage.extensions.includes(extension)){
```
Comment (kburtram) [inline src/vs/editor/common/services/languagesRegistry.ts]: we generally try to make minimal changes to the VS Code under the ../vs/ directory to make it easier to take VS Code source code refreshes.  I wonder if there is a way to fix this issue without requiring changes to the forked VS Code source code, such as not registering SQL twice (assuming that's what's happening here).  Let me take a look and see what's happening here.

Comment (anthonydresser) [reply src/vs/editor/common/services/languagesRegistry.ts]: This looks like a change that should go straight to vscode sources, unless theres a reason they aren't.
