### PR TITLE
reverting row which escape is clicked and fixed the issue with reverting rows

### LINKED ISSUE #1332: Edit data revert row doesn't work
- SQL Operations Studio Version:

Steps to Reproduce:

1. Create a table with following script

CREATE TABLE [dbo].[TestTable](
	[c1] [int] NOT NULL,
	[c2] [int] NULL,
 )
Insert into TestTable (c1, c2) values (1, 1)
Insert into TestTable (c1, c2) values (2, 2)
2.  Open the edit table document for the table
3.Try to edit the first row by adding a string to the second column
4. verify it fails and try to revert the row (Escape or right click Revert)

Expected: Row should get reverted 
Actual: the row value is reverted (With right click Revert, Escape doesn't work)
but clicking on any row tries to update the row with previous data

### PR DESCRIPTION
**Pull request by llali**
fixes #1332

### CODE REVIEW

File: src/sql/parts/grid/views/editData/editData.component.ts [hunk 1]
```diff
@@ -228,7 +236,7 @@ export class EditDataComponent extends GridParentComponent implements OnInit, On
 
 		let cellSelectTasks: Promise<void> = Promise.resolve();
 
-		if (this.currentCell.isEditable && this.currentEditCellValue !== null && !this.removingNewRow) {
+		if (this.currentCell.isEditable && this.currentEditCellValue !== null && !this.removingNewRow && !this.revertingRow) {
```
Comment (MattIrv) [inline src/sql/parts/grid/views/editData/editData.component.ts]: why is `this.revertingRow` necessary? We won't enter this if statement anyway because the new code sets `this.currentEditCellValue` to null as soon as you hit escape.

Is it because this method is getting called when we call `self.focusCell` in `onRevertRow()`? In that case we could just set `this.currentEditCellValue` to null before calling `focusCell`

File: src/sql/parts/grid/views/editData/editData.component.ts [hunk 2]
```diff
@@ -415,6 +423,10 @@ export class EditDataComponent extends GridParentComponent implements OnInit, On
 					this.newRowVisible = false;
 				});
 			handled = true;
+		} else if (e.keyCode === jQuery.ui.keyCode.ESCAPE) {
+			this. revertingRow= true;
```
Comment (MattIrv) [inline src/sql/parts/grid/views/editData/editData.component.ts]: spacing
