### PR TITLE
Fix few issues in dashboard command center

### LINKED ISSUE #630: Dashboard: add tab shouldn't work if none selected
- SQL Operations Studio Version:

Steps to Reproduce:
- Open a dashboard when you have 0 available tab contributions
- Hit the `+` button to open the add tab dialog
- Hit the Add button
- Get an error!

Expected:
- Button should be disabled & code should handle undefined input

### PR DESCRIPTION
**Pull request by AbbiePetcht**
- fix #630: Dashboard: add tab shouldn't work if none selected 
- show possible tab IDs in the setting file
- check number of widget in dashboardWidgetWrapper.component.ts (regression)

### CODE REVIEW

File: src/sql/parts/dashboard/dashboardConfig.contribution.ts [hunk 1]
```diff
@@ -4,12 +4,13 @@
  *--------------------------------------------------------------------------------------------*/
 import { Registry } from 'vs/platform/registry/common/platform';
 import { IConfigurationRegistry, Extensions, IConfigurationNode } from 'vs/platform/configuration/common/configurationRegistry';
+import { DASHBOARD_CONFIG_ID } from 'sql/parts/dashboard/pages/dashboardPagecontribution';
```
Comment (kevcunnane) [inline src/sql/parts/dashboard/dashboardConfig.contribution.ts]: This line is causing the Linux build to fail - paths are case sensitive there and you lowercases `contribution`
