### PR TITLE
Fix issue where loading unsave sql file open as untitiledEditorInput

### LINKED ISSUE #356: After hot exit, editors display connection/query results incorrectly when switching tabs
- SQL Operations Studio Version: December 18 RC 1

Steps to Reproduce:
1. Open a new query tab, optionally saving it (this repros for both saved and unsaved editors)
2. Close SQL Ops Studio with hot exit enabled and then reopen it. Your editor should still be open
3. Connect in the editor. You can do things like run queries. Do not save
4. Switch to another tab or open a new tab, then switch back to the original tab

Expected behavior: The original tab still displays its connection and query results correctly
Actual behavior: The original tab appears as if it no longer has a connection, though you can still run the query by clicking the "Run" button or using the command palette, and Intellisense still works. If you had executed a query in that tab, the results disappear
Workaround: Save the query after starting from hot exit

It looks like editors are opened as instances of `UntitledEditorInput` when reopening from hot exit, when they should be instances of `QueryInput`, which seems to be related to this issue.

Repros on Mac, Linux, and Windows.

out

### PR DESCRIPTION
**Pull request by AbbiePetcht**
Fix #356, After hot exit, editors display connection/query results incorrectly when switching tabs

### CODE REVIEW

File: src/vs/workbench/browser/parts/editor/editor.contribution.ts [hunk 1]
```diff
@@ -132,15 +136,21 @@ class UntitledEditorInputFactory implements IEditorInputFactory {
 		return JSON.stringify(serialized);
 	}
 
-	public deserialize(instantiationService: IInstantiationService, serializedEditorInput: string): UntitledEditorInput {
-		return instantiationService.invokeFunction<UntitledEditorInput>(accessor => {
+	public deserialize(instantiationService: IInstantiationService, serializedEditorInput: string): EditorInput {
```
Comment (anthonydresser) [inline src/vs/workbench/browser/parts/editor/editor.contribution.ts]: Why do we need to change the type definition on this?

File: src/vs/workbench/browser/parts/editor/editor.contribution.ts [hunk 2]
```diff
@@ -132,15 +136,21 @@ class UntitledEditorInputFactory implements IEditorInputFactory {
...
+		return instantiationService.invokeFunction<EditorInput>(accessor => {
 			const deserialized: ISerializedUntitledEditorInput = JSON.parse(serializedEditorInput);
 			const resource = !!deserialized.resourceJSON ? URI.revive(deserialized.resourceJSON) : URI.parse(deserialized.resource);
 			const filePath = resource.scheme === 'file' ? resource.fsPath : void 0;
 			const language = deserialized.modeId;
 			const encoding = deserialized.encoding;
 
-			return accessor.get(IWorkbenchEditorService).createInput({ resource, filePath, language, encoding }) as UntitledEditorInput;
+			let input = accessor.get(IWorkbenchEditorService).createInput({ resource, filePath, language, encoding }) as UntitledEditorInput;
```
Comment (kburtram) [inline src/vs/workbench/browser/parts/editor/editor.contribution.ts]: please add `// {{SQL CARBON EDIT}}` before each edit block in `vs/` source files.

File: src/vs/workbench/browser/parts/editor/editor.contribution.ts (hunk 1 above)
Comment (AbbiePetcht) [reply src/vs/workbench/browser/parts/editor/editor.contribution.ts]: If it's sql file, it needs to return as QueryResultsInput, otherwise return as UntitledEditorInput type. UntitledEditorInput doesn't understand connection

---
In reply to: [158188741](https://github.com/Microsoft/sqlopsstudio/pull/385#discussion_r158188741) [](ancestors = 158188741)
