### PR TITLE
Fix bar chart displaying extra series

### LINKED ISSUE #1228: The legend in vertical data is incorrect (vertical bar chart)
When use columns name as labels, it should not include the first column
image

### PR DESCRIPTION
**Pull request by MattIrv**
Fixes #1228 

Bar charts use the first column of results as y (horizontal) or x (vertical) axis label names in the "vertical" data mode, but our logic didn't properly remove that column as a series for the data

### CODE REVIEW

File: src/sql/parts/dashboard/widgets/insights/views/charts/chartInsight.component.ts [hunk 1]
```diff
@@ -255,17 +255,17 @@ export abstract class ChartInsight extends Disposable implements IInsightsView {
 			}
 		} else {
 			if (this._config.columnsAsLabels) {
-				return this._data.rows[0].map((row, i) => {
+				return this._data.rows[0].slice(1).map((row, i) => {
```
Comment (anthonydresser) [inline src/sql/parts/dashboard/widgets/insights/views/charts/chartInsight.component.ts]: Why if we are using the columns as the labels should we cut off the first column?

Comment (MattIrv) [reply src/sql/parts/dashboard/widgets/insights/views/charts/chartInsight.component.ts]: This config option is really "column names as series labels". Whether it's true or not we use the data in the first column as an axis label, so we shouldn't include it as actual data

Comment (anthonydresser) [reply src/sql/parts/dashboard/widgets/insights/views/charts/chartInsight.component.ts]: The problem is running `select 1 as A` and trying to use the chart viewer will cause it to crash. Which is I removed this in the first place. I think fixing the chart insight is a bigger deal than running `select 1 as A` so we should probably merge this in, however, we should reopen that bug and think through this further.

Comment (MattIrv) [reply src/sql/parts/dashboard/widgets/insights/views/charts/chartInsight.component.ts]: `slice` returns an empty array in that case so this block of code behaves fine. It does crash since then there's no data for the chart to display, but that will be handled by #1226 so I don't think there's any more work here

Comment (anthonydresser) [reply src/sql/parts/dashboard/widgets/insights/views/charts/chartInsight.component.ts]: The problem is I would expect `select 1 as a` would use a single 1 as a data point for the graphs. Its an edge case, but functionally thats what it should do.
