### PR TITLE
Fix edit data revert row bugs

### LINKED ISSUE #1498: Edit data "revert row" fails on new rows
- SQL Operations Studio Version: master 8fce79f

Steps to Reproduce:
1. Open edit data for a table
2. Start to add a new row but do not commit it
3. Click on one of the modified cells for the new row and choose "revert row"

Expected behavior: The new row is removed
Actual behavior: The table goes blank and the following error appears:

```
Update cell failed: Start row cannot be less than 0 or greater than the number of rows in the result set Parameter name: rowId
zone-node.js:2251
Unhandled Promise rejection: Cannot read property 'values' of undefined ; Zone: <root> ; Task: Promise.then ; Value:
zone-node.js:2251
TypeError: Cannot read property 'values' of undefined

TypeError: Cannot read property 'values' of undefined
    at Function.getDataWithSchema (/Users/mairvine/code/sqlopsstudio/node_modules/angular2-slickgrid/out/js/slickGrid.js:473:52)
    at dataRows.dataRows.getRange.map.d (/Users/mairvine/code/sqlopsstudio/node_modules/angular2-slickgrid/out/js/slickGrid.js:190:40)
    at Array.map (native)
    at Object.getRange (/Users/mairvine/code/sqlopsstudio/node_modules/angular2-slickgrid/out/js/slickGrid.js:189:88)
    at getDataRange (/Users/mairvine/code/sqlopsstudio/node_modules/slickgrid/slick.grid.js:1630:21)
    at renderRowRange (/Users/mairvine/code/sqlopsstudio/node_modules/slickgrid/slick.grid.js:2408:21)
    at SlickGrid.render (/Users/mairvine/code/sqlopsstudio/node_modules/slickgrid/slick.grid.js:2557:11)
    at SlickGrid.invalidateRange (/Users/mairvine/code/sqlopsstudio/node_modules/angular2-slickgrid/out/js/slickGrid.js:486:20)
    at SlickGrid.renderGridDataRowsRange (/Users/mairvine/code/sqlopsstudio/node_modules/angular2-slickgrid/out/js/slickGrid.js:608:14)
    at VirtualizedCollection.dataRows.setCollectionChangedCallback [as collectionChangedCallback] (/Users/mairvine/code/sqlopsstudio/node_modules/angular2-slickgrid/out/js/slickGrid.js:600:22)
zone-node.js:2251
[Extension Host] [Error - 4:41:16 PM] Request edit/updateCell failed. (at CustomOutputChannel.appendLine (/Users/mairvine/code/sqlopsstudio/extensions/mssql/out/main.js:189:17))
zone-node.js:2251
[Extension Host]   Message: Start row cannot be less than 0 or greater than the number of rows in the result set
zone-node.js:2251
Parameter name: rowId
  Code: 0  (at CustomOutputChannel.appendLine (/Users/mairvine/code/sqlopsstudio/extensions/mssql/out/main.js:189:17))
```

### LINKED ISSUE #1501: Hitting enter while in the last existing edit data row creates a new row that it tries to commit
- SQL Operations Studio Version: Master 8fce79f

Steps to Reproduce:
1. Open edit data and choose a cell in the last existing row to edit
2. Edit the cell and hit enter
3. Click off of the new row that appears

Expected behavior: The unedited new row does not get committed (like SSMS)
Actual behavior: The new row gets committed 

Editing the new row after hitting enter in the "504" cell above it. If I click outside of the new row now it tries to commit it.
Blank new row that will be committed when clicking outside of it

Workaround is to hit the "run" button to refresh the table before clicking off of the new row

### PR DESCRIPTION
**Pull request by MattIrv**
This fixes #1498 and #1502 by updating the revert row logic so that it does not try to send the current edit to the service before calling revert (which caused problems when the current edit was not valid) and by unifying the "revert row" context menu logic with the escape key handler logic to revert the current row, since there is no way to have active changes for any other row.

Also fixes #1501 by adding logic to delete a new row instead of committing it when clicking off of it onto an existing row if there are no changes. The user can still commit a new blank row by clicking to add another new row.

### CODE REVIEW

File: src/sql/parts/grid/views/editData/editDataGridActions.ts [hunk 1]
```diff
@@ -56,18 +56,18 @@ export class DeleteRowAction extends Action {
 
 export class RevertRowAction extends Action {
 	public static ID = 'grid.revertRow';
-	public static LABEL = localize('revertRow', 'Revert Row');
+	public static LABEL = localize('revertRow', 'Revert Current Row');
```
Comment (anthonydresser) [inline src/sql/parts/grid/views/editData/editDataGridActions.ts]: Does this mean there is no way to revert a row that isn't currently selected?

Comment (MattIrv) [reply src/sql/parts/grid/views/editData/editDataGridActions.ts]: Correct. There's no way to have edits in a row that is not currently selected as far as I'm aware, so let me know if you think that's possible but otherwise it shouldn't be a problem.

Comment (anthonydresser) [reply src/sql/parts/grid/views/editData/editDataGridActions.ts]: I guess I always assumed you could revert changes you have made previously in the session, but maybe not.

**Comment by MattIrv** [comment]
Just pushed some new changes that will fix #1501 as well as a new bug I discovered in the process where the "delete row" context menu option didn't work when adding a new row

**Comment by kburtram** [comment]
@MattIrv I'm going to produce an insiders build now for June sign-off testing.  I'll merge this to get included in that build.  Please push any follow-ups in a new PR.  Thanks!
