### PR TITLE
Fix custom UI validation bugs

### LINKED ISSUE #1581: Custom UI Input Box validations are broken
- SQL Operations Studio Version: master 0bf642d

Steps to Reproduce:
1. Open a custom dialog that has an input box with a validation
2. Enter invalid input into the box

Expected behavior: The input box gets styled correctly to show that it is not valid and validity changed events fire correctly
Actual behavior: The validation does not appear to do anything

### PR DESCRIPTION
**Pull request by MattIrv**
Fixes #1581 

There were 2 problems here. One was that input box validation broke because I resolved a merge conflict incorrectly when merging the VS Code release. The other was that my recent refactoring to how components handle events inadvertently stopped the `onValidityChanged` event from ever firing for any component.

### CODE REVIEW

File: src/vs/base/browser/ui/inputbox/inputBox.ts [hunk 1]
```diff
@@ -364,7 +364,11 @@ export class InputBox extends Widget {
 				};
 			}
 
-			if (!errorMsg) {
+			if (errorMsg) {
+				this.inputElement.setAttribute('aria-invalid', 'true');
+				this.showMessage(errorMsg);
+			}
+			else if (this.inputElement.hasAttribute('aria-invalid')) {
```
Comment (MattIrv) [inline src/vs/base/browser/ui/inputbox/inputBox.ts]: This code matches what's in VS Code's version of `inputBox.ts` now so it doesn't need "{{SQL CARBON EDIT}}" tags. The only reason it didn't match before is because I resolved a merge conflict (created because the block of code above this is actually something we edited) incorrectly.
